import { Link } from 'react-router-dom';

const brands = ['SAMSUNG', 'Croma', 'Reliance Digital', 'vijay sales', 'hp', 'ASUS'];
const benefits = [['◈', '0% Interest', 'Repay only what you spend.'], ['⌁', 'Keep growing', 'Your mutual funds stay invested.'], ['◉', 'Quick approvals', 'Instant eligibility check.'], ['✦', 'No extra charges', 'Simple, transparent terms.']];

export default function Home() {
  return <div className="mx-auto max-w-6xl px-3 py-4 sm:px-6 sm:py-8">
    <div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold text-[#6d28d9]">GOOD MORNING</p><h1 className="text-xl font-extrabold sm:text-2xl">Your 1Fi dashboard</h1></div><span className="rounded-full bg-[#f1edff] px-3 py-1.5 text-xs font-bold text-[#6d28d9]">• Active</span></div>
    <div className="grid gap-4 lg:grid-cols-[1.35fr_.9fr]">
      <section className="space-y-4">
        <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-[#7431d8] via-[#6d20da] to-[#3c0a89] p-5 text-white shadow-[0_12px_26px_rgba(91,25,185,.25)] sm:p-7"><div className="absolute -right-8 -top-12 h-44 w-44 rounded-full border-[22px] border-white/10"/><div className="absolute bottom-2 right-5 rotate-[-15deg] text-5xl font-black italic text-white/90 sm:text-7xl">0%</div><span className="inline-block rounded bg-[#08bb61] px-2 py-1 text-xs font-bold">▣ LIMIT AVAILABLE</span><p className="mt-3 text-2xl font-extrabold sm:text-3xl text-wrap text-balance">₹1,56,091</p><p className="text-xs font-medium text-white/70">REMAINING TO SPEND</p><p className="mt-5 max-w-48 text-sm font-black leading-tight">Get 0% interest on every purchase</p><Link to="/shop" className="mt-4 inline-block rounded-full bg-white px-4 py-2 text-xs font-bold text-[#6325ce]">Shop now</Link></div>
        <div className="flex items-center gap-3 rounded-2xl bg-white p-3 shadow-card ring-1 ring-[#eeeaf4]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f0eaff] text-[#6d28d9]">▣</span><p className="min-w-0 flex-1 text-xs"><b className="block text-[#2a2630]">Don't miss a payment</b><span className="text-[#8d8795]">Set autopay with UPI, Paytm, PhonePe, GPay</span></p><button className="rounded-full border border-[#8c4df0] px-3 py-1 text-xs font-bold text-[#6928d8]">Setup</button></div>
        <div className="overflow-hidden rounded-2xl bg-[#082c55] p-5 text-white shadow-card"><p className="text-xs font-bold tracking-widest text-[#b6d7ff]">EVERYDAY PRO PERFORMANCE</p><p className="mt-1 max-w-56 text-base font-extrabold">Got Your New MacBook for Work</p><p className="mt-3 inline-block rounded-full bg-white/15 px-3 py-1 text-xs font-bold">Starts at ₹2900/mo</p><div className="mt-4 h-1.5 w-24 rounded-full bg-white/25"><div className="h-full w-1/3 rounded-full bg-[#a676ff]"/></div></div>
        <BlockTitle>OUR BRAND PARTNERS</BlockTitle><div className="grid grid-cols-3 gap-2 sm:grid-cols-6">{brands.map(b => <div key={b} className="grid h-14 place-items-center rounded-xl bg-white p-2 text-center text-xs font-black text-[#7a7480] shadow-card">{b}</div>)}</div>
        <BlockTitle>WHY PAY WITH 1FI</BlockTitle><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{benefits.map(([icon, title, text]) => <div className="rounded-xl bg-white p-3 shadow-card" key={title}><span className="text-[#7c3aed]">{icon}</span><b className="mt-1 block text-xs">{title}</b><p className="mt-1 text-xs leading-tight text-[#918b97]">{text}</p></div>)}</div>
      </section>
      <aside className="space-y-4"><div className="rounded-2xl bg-white p-5 shadow-card"><p className="text-xs font-bold text-[#6d28d9]">YOUR EMI AT A GLANCE</p><div className="mt-4 grid grid-cols-2 gap-3"><Stat label="Total outstanding" value="₹1,220"/><Stat label="Active loans" value="1"/></div><div className="mt-4 rounded-xl bg-[#f5f1ff] p-3"><p className="text-xs text-[#6e6780]">Upcoming EMI · 7 Aug</p><b className="text-lg text-[#6d28d9]">₹407</b><button className="float-right rounded-full bg-[#6d28d9] px-3 py-1.5 text-xs font-bold text-white">Pay Now</button></div></div><div className="rounded-2xl bg-white p-5 shadow-card"><p className="text-xs font-bold text-[#6d28d9]">QUICK ACTIONS</p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs font-semibold">{[['＋','Pledge More'],['⌕','Remove Pledge'],['◷','Pledge History']].map(([i,t])=><button key={t} className="rounded-xl bg-[#faf8ff] p-3 text-[#6d28d9]"><span className="block text-lg">{i}</span><span className="text-[#5e5867]">{t}</span></button>)}</div></div><div className="rounded-2xl bg-white p-5 shadow-card"><p className="text-xs font-bold text-[#6d28d9]">HOW 1FI WORKS</p>{['Pledge mutual funds securely','Choose a product and EMI plan','Pay easily each month'].map((s,i)=><div className="mt-4 flex gap-3 text-xs" key={s}><b className="grid h-6 w-6 place-items-center rounded-full bg-[#eee7ff] text-[#6d28d9]">{i+1}</b><span className="pt-1 text-[#645d6d]">{s}</span></div>)}</div></aside>
    </div>
  </div>;
}
function BlockTitle({children}) { return <p className="border-l-2 border-[#7c3aed] pl-2 text-xs font-extrabold tracking-[.16em] text-[#7c3aed]">{children}</p>; }
function Stat({label,value}) { return <div className="rounded-xl bg-[#faf9fc] p-3"><p className="text-xs uppercase text-[#8b8494]">{label}</p><p className="mt-1 text-lg font-extrabold">{value}</p></div>; }